501: '商品管理番号'
502: '商品名'
503: '販売価格'
504: '全商品ディレクトリID'
505: '商品情報レイアウト'
506: '消費税'
507: '送料'
508: '代引き手数料'
509: '在庫タイプ'
510: '注文受付数'
511: '倉庫指定'
512: '注文ボタン'
513: '資料請求ボタン'
514: '商品問い合わせボタン'
515: 'モバイル表示'
516: 'のし対応'
517: 'ポイント変倍率'
518: 'ポイント変倍適応期間(開始)'
518: 'ポイント変倍適応期間(終了)'
519: '商品画像名（ALT）'
520: '商品番号'
521: 'PC用商品説明文'
522: 'モバイル用商品説明文'
523: '表示価格'
524: '商品画像URL'
525: '動画URL'
526: 'PC用キャッチコピー'
527: 'モバイル用キャッチコピー'
528: 'PC用販売説明文'
529: '個別送料'
530: '送料区分１'
531: '送料区分２'
532: '期間限定販売フラグ'
532: '期間限定販売開始日'
532: '期間限定販売終了日'
534: '在庫数表示'
535: '項目選択肢別在庫用縦軸選択肢項目名'
536: '項目選択肢別在庫用横軸選択肢項目名'
537: '項目選択肢別在庫用残り表示閾値'
540: 'カタログID'
542: '在庫切れ時の注文受付'
543: '在庫あり時納期管理番号'
544: '在庫切れ時納期管理番号'
552: 'タグID'
553: 'レビュー表示'
554: 'あす楽配送管理番号'
556: 'サイズ表リンクコード'
564: '再入荷のお知らせボタン'
565: 'サーチ非表示'
566: '医薬品説明文'
567: '医薬品注意事項'
568: '二重価格文言ID'
570: 'スマートフォン用商品説明文'
702: '選択肢スタイル'
703: 'Select/Checkbox用項目名'
704: 'Select/Checkbox用選択肢'
705: '項目選択肢別在庫用横軸選択肢'
706: '項目選択肢別在庫用横軸選択肢子番号'
707: '項目選択肢別在庫用縦軸選択肢'
708: '項目選択肢別在庫用縦軸選択肢子番号'
709: '項目選択肢別在庫用取り寄せ可能表示'
710: '在庫数'
711: '在庫戻し設定'
