N000: 正常に処理が終了しました。
S001: 只今メンテナンス中のためアクセスできません。
S002: 只今メンテナンス中のためアクセスできません。
S011: システムエラー
S021: システムエラー
S031: システムエラー
S999: システムエラー
C001: 該当する商品IDは存在しません。
C011: 指定された店舗IDは存在しません。
C113: パラメータがフォーマットにそっていません。
C114: 商品一括登録サービスにロックされているため操作できません。
C201: 指定されたイベントIDは存在しません。
C204: 商品IDのフォーマットが正しくありません。
C219: 不要なデータが入っています。
C301: 登録・更新・削除時 渡されたtransactionIDでの更新が既にされています。
